/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knightstour.giaodien;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import knightstour.AutoPlay.chess.KnightTours_Automatic;
import knightstour.giaodien.GameMode;
import java.awt.event.KeyListener;
import knightstour.Player.Board;
import knightstour.Player.KnightTous_Player;


/**
 *
 * @author My Pc
 */
public class Play extends javax.swing.JFrame {

   

    /**
     * Creates new form NguoiChoi
     */
    
  
    public Play() {
        initComponents();
        CheckPoint ten = new CheckPoint(DatTen.getText());
}
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatTen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đặt tên người chơi");
        setMinimumSize(new java.awt.Dimension(620, 350));
        setPreferredSize(new java.awt.Dimension(620, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DatTen.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DatTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatTenActionPerformed(evt);
            }
        });
        getContentPane().add(DatTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 330, 43));

        jLabel1.setBackground(new java.awt.Color(153, 153, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setLabelFor(DatTen);
        jLabel1.setText("Đặt tên người chơi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 60));

        back.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(102, 51, 0));
        back.setText("Quay lại");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 170, 50));

        next.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        next.setForeground(new java.awt.Color(102, 51, 0));
        next.setText("Tiếp Theo");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 160, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/z3758228332941_2dc68cefbeff8d1a5a29e03ccca59803.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DatTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatTenActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_DatTenActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        GameMode b = new GameMode();
       b.setVisible(true);
       
       this.setVisible(false);

    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
      
        
        
         String ten = DatTen.getText().trim();
        
              if(ten.equals("")){
            JOptionPane.showMessageDialog(rootPane,
                     "Tên không được rỗng\n");
              }
              else {     
//                this.setVisible(false);
                KnightTous_Player demo = new KnightTous_Player();
                demo.setVisible(true);
              
              }
              
               CheckPoint getTen = new CheckPoint(DatTen.getText());
               getTen.setVisible(true);
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Play().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DatTen;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
